package net.craftventure.bukkit.ktx

import net.craftventure.bukkit.ktx.extension.updateMeta
import org.bukkit.Material
import org.bukkit.inventory.ItemStack
import org.bukkit.inventory.meta.ItemMeta

object MaterialConfig {
    val FENRIR_FRONT get() = dataItem(Material.DIAMOND_SWORD, 1)
    val FENRIR_CAR get() = dataItem(Material.DIAMOND_SWORD, 2)
    val RAPID get() = dataItem(Material.DIAMOND_SWORD, 3)
    val TEACUP get() = dataItem(Material.DIAMOND_SWORD, 4)
    val LOGFLUME get() = dataItem(Material.DIAMOND_SWORD, 5)
    val TLALOC_ARM get() = dataItem(Material.DIAMOND_SWORD, 6)
    val TLALOC_ARM_JOINT get() = dataItem(Material.DIAMOND_SWORD, 7)
    val TLALOC_CENTER_CAR get() = dataItem(Material.DIAMOND_SWORD, 8)
    val TLALOC_SIDE_CAR get() = dataItem(Material.DIAMOND_SWORD, 9)
    val PPL_CAR get() = dataItem(Material.DIAMOND_SWORD, 10)
    val KART_OLDTIMER get() = dataItem(Material.DIAMOND_SWORD, 11)
    val DIVE_COASTER get() = dataItem(Material.DIAMOND_SWORD, 12)
    val VIKING_SHIP_MID get() = dataItem(Material.DIAMOND_SWORD, 13)
    val VIKING_SHIP_END get() = dataItem(Material.DIAMOND_SWORD, 14)
    val VIKING_SHIP_FRAME get() = dataItem(Material.DIAMOND_SWORD, 15)
    val RAPID_LIFT get() = dataItem(Material.DIAMOND_SWORD, 16)
    val FENRIR_CAR_WITHOUT_BACK_SEATS get() = dataItem(Material.DIAMOND_SWORD, 17)
    val FENRIR_CAR_WITHOUT_FRONT_SEATS get() = dataItem(Material.DIAMOND_SWORD, 18)
    val TEACUP_DISK get() = dataItem(Material.DIAMOND_SWORD, 19)
    val CCR_CAR get() = dataItem(Material.DIAMOND_SWORD, 20)
    val CCR_LOCO get() = dataItem(Material.DIAMOND_SWORD, 21)
    val GON_BAO_BENCH get() = dataItem(Material.DIAMOND_SWORD, 22)
    val EAGLE_FURY_SEAT get() = dataItem(Material.DIAMOND_SWORD, 23)
    val FENG_HUANG_CAR get() = dataItem(Material.DIAMOND_SWORD, 24)
    val SM_FRONT get() = dataItem(Material.DIAMOND_SWORD, 25)
    val SM_NORMAL get() = dataItem(Material.DIAMOND_SWORD, 26)
    val KART_RACER get() = dataItem(Material.DIAMOND_SWORD, 27)
    val SEASOULS_BOAT get() = dataItem(Material.DIAMOND_SWORD, 28)
    val FENG_HUANG_CAR_NO_RIGHT_SEAT get() = dataItem(Material.DIAMOND_SWORD, 29)
    val FENG_HUANG_CAR_NO_LEFT_SEAT get() = dataItem(Material.DIAMOND_SWORD, 30)
    val HYPERION_ZEPPELIN get() = dataItem(Material.DIAMOND_SWORD, 31)
    val SOARIN get() = dataItem(Material.DIAMOND_SWORD, 32)
    val INDIANA_JONES get() = dataItem(Material.DIAMOND_SWORD, 33)
    val KART_SPONGEBOB_BURGER get() = dataItem(Material.DIAMOND_SWORD, 34)
    val KART_GOLF_CADDY get() = dataItem(Material.DIAMOND_SWORD, 35)
    val PLACE_HOLDER get() = dataItem(Material.DIAMOND_SWORD, 36)
    val WHEELCHAIR_KART get() = dataItem(Material.DIAMOND_SWORD, 37)
    val OUZO_CAR get() = dataItem(Material.DIAMOND_SWORD, 53)
    val ROCKTOPUS_ARM get() = dataItem(Material.DIAMOND_SWORD, 56)
    val ROCKTOPUS_CAR get() = dataItem(Material.DIAMOND_SWORD, 57)
    val ROCKTOPUS_DISC get() = dataItem(Material.DIAMOND_SWORD, 58)
    val PLAYER_PLACEHOLDER get() = dataItem(Material.DIAMOND_SWORD, 59)
    val DOLPHIN_AMUSE_CAR get() = dataItem(Material.DIAMOND_SWORD, 60)
    val DOLPHIN_AMUSE_CAR_ANIMATED get() = dataItem(Material.DIAMOND_SWORD, 61)
    val DOLPHIN_AMUSE_ARM get() = dataItem(Material.DIAMOND_SWORD, 62)
    val ROK_PERSON get() = dataItem(Material.DIAMOND_SWORD, 63)
    val VR_REAR get() = dataItem(Material.DIAMOND_SWORD, 64)
    val KART_ROK get() = dataItem(Material.DIAMOND_SWORD, 65)
    val JEEP_SAFARIJEEP get() = dataItem(Material.DIAMOND_SWORD, 70)
    val EUROBAT_MID get() = dataItem(Material.DIAMOND_SWORD, 72)
    val EUROBAT_FRONT get() = dataItem(Material.DIAMOND_SWORD, 73)
    val BONE_RATTLER get() = dataItem(Material.DIAMOND_SWORD, 74)
    val KART_SLEIGH get() = dataItem(Material.DIAMOND_SWORD, 75)
    val KART_SANTA_SLEIGH get() = dataItem(Material.DIAMOND_SWORD, 76)
    val SKYFOOGLE get() = dataItem(Material.DIAMOND_SWORD, 78)
    val SWINGRIDE_CHAIR get() = dataItem(Material.DIAMOND_SWORD, 79)
    val MM18 get() = dataItem(Material.DIAMOND_SWORD, 80)
    val COOKIE_RIDE get() = dataItem(Material.DIAMOND_SWORD, 81)
    val VR_FRONT get() = dataItem(Material.DIAMOND_SWORD, 82)
    val VR_NORMAL get() = dataItem(Material.DIAMOND_SWORD, 83)
    val KART_DEFAULT get() = dataItem(Material.DIAMOND_SWORD, 84)
    val KART_HYPERION get() = dataItem(Material.DIAMOND_SWORD, 85)
    val SKYFOOGLE_SUMMER get() = dataItem(Material.DIAMOND_SWORD, 97)
    val KART_LOWRIDER get() = dataItem(Material.DIAMOND_SWORD, 98)
    val VLADIMIR_TOP get() = dataItem(Material.DIAMOND_SWORD, 99)
    val VLADIMIR_BOTTOM get() = dataItem(Material.DIAMOND_SWORD, 100)
    val CAULDRON_KART get() = dataItem(Material.DIAMOND_SWORD, 104)
    val SKILIFT get() = dataItem(Material.DIAMOND_SWORD, 105)
    val WINTER_SLEIGH get() = dataItem(Material.DIAMOND_SWORD, 106)
    val WINTER_SCHLITTEN get() = dataItem(Material.DIAMOND_SWORD, 107)
    val SNOW_TUBE get() = dataItem(Material.DIAMOND_SWORD, 108)
    val KART_BEERBRAWL get() = dataItem(Material.DIAMOND_SWORD, 126)
    val KART_CHASSIS get() = dataItem(Material.DIAMOND_SWORD, 127)
    val KART_WHEEL get() = dataItem(Material.DIAMOND_SWORD, 128)
    val KART_PARROT get() = dataItem(Material.DIAMOND_SWORD, 129)
    val MINECART get() = dataItem(Material.DIAMOND_SWORD, 135)
    val CHERNOLUTION_FRONT get() = dataItem(Material.DIAMOND_SWORD, 136)
    val CHERNOLUTION_NORMAL get() = dataItem(Material.DIAMOND_SWORD, 137)
    val TANK_BARREL get() = dataItem(Material.DIAMOND_SWORD, 138)
    val TANK_HULL get() = dataItem(Material.DIAMOND_SWORD, 139)
    val TANK_TURRET get() = dataItem(Material.DIAMOND_SWORD, 140)
    val ALPHADERA_CAR get() = dataItem(Material.DIAMOND_SWORD, 142)
    val KART_TRACER get() = dataItem(Material.DIAMOND_SWORD, 143)
    val KART_TRACER_TRACE get() = dataItem(Material.DIAMOND_SWORD, 144)
    val KART_SCOOTER get() = dataItem(Material.DIAMOND_SWORD, 145)
    val KART_BEE get() = dataItem(Material.DIAMOND_SWORD, 146)

    val CASINO_ARROW get() = dataItem(Material.DIAMOND_HOE, 27)
    val CASINO_WOF get() = dataItem(Material.DIAMOND_HOE, 145)
    val CANDY_CANE get() = dataItem(Material.IRON_SWORD, 5)

    val ARM get() = dataItem(Material.DIAMOND_SWORD, 95)

    val GUI_ESTOP_OFF get() = dataItem(Material.IRON_SWORD, 9)
    val GUI_ESTOP_ON get() = dataItem(Material.IRON_SWORD, 10)
    val OUZO_BOTTLE_ITEM get() = dataItem(Material.IRON_SWORD, 11)
    val GUI_BALLOON get() = dataItem(Material.IRON_SWORD, 19)
    val GUI_BOOTS get() = dataItem(Material.IRON_SWORD, 20)
    val GUI_CHESTPLATE get() = dataItem(Material.IRON_SWORD, 21)
    val GUI_HAND get() = dataItem(Material.IRON_SWORD, 22)
    val GUI_HELMET get() = dataItem(Material.IRON_SWORD, 23)
    val GUI_LEGGINGS get() = dataItem(Material.IRON_SWORD, 24)
    val GUI_SHIELD get() = dataItem(Material.IRON_SWORD, 25)
    val GUI_TITLE get() = dataItem(Material.IRON_SWORD, 50)
    val GUI_COSTUME get() = dataItem(Material.IRON_SWORD, 51)
    val GUI_GUN get() = dataItem(Material.IRON_SWORD, 22)//52)
    val GUI_SHOULDER_PET get() = dataItem(Material.IRON_SWORD, 22)
    val GUI_INSTRUMENT get() = dataItem(Material.IRON_SWORD, 22)

    val GUI_BUTTON_BLINKING get() = dataItem(Material.POTION, 4)
    val GUI_BUTTON_OFF get() = dataItem(Material.POTION, 6)
    val GUI_BUTTON_ON get() = dataItem(Material.POTION, 5)
    val GUI_SWITCH_OFF get() = dataItem(Material.POTION, 8)
    val GUI_SWITCH_ON get() = dataItem(Material.POTION, 7)

    fun dataItem(material: Material, data: Int) = ItemStack(material).updateMeta<ItemMeta> {
        setCustomModelData(data)
    }
}
